### ISSUE TITLE
Revise dataset.py structure

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/modelforge#349]
Currently, each of the supported datasets are defined in their own class that inherits from the HDF5Dataset class.  Each of these classes provides information about each dataset:
- properties available within the dataset
- default properties of interest
- properties of interest (to actually use)
- properties association (which specifies the type of each quantity, used for unit conversion)
- atomic self energies 

Previously, these also included the links to the files to download (and checksums) for each version, however these were moved into yaml files (see PR #117).  

To allow control over the properties used in training, definition of properties of interest and the association of individual keys in the dataset with internal variables (i.e., E: total_energy, positions: geometry, etc.), pydantic models were added that require these to be defined in the .toml runtime files (See PR #327 ); this makes much of what is currently in the dataset specific classes some what unnecessary. 

Plan: 

A better, more flexible approach would be to move the atomic self energies and  the available properties to the yaml files.  Initialization of the HDF5Dataset class would simply accept which dataset to use.  

The new dataset API now includes information about each property needed to validate units (i.e., ensuring that an energy property has the appropriate energy units we expect). I think moving the GlobalUnitSystem class defined in the curate module to the main repo and utilizing this during dataset loading would remove some of the hackiness currently in the code.  I also think that, the meat of the HDF5Dataset class (responsible for reading/parsing the dataset) could largely be replaced with the Dataset API. Basically reading the HDF5 file back into an instance of SourceDataset, allow the use of the dataset api for validation of the inputs.  that would also make it easier to perform future manipulation/subsetting of the dataset (see issues #306 and #329 ) as there is lots of functionality built into source dataset. 

Note: this would eliminate the current backwards compatibility with the older datasets, so it just requires that I also get all the newly curated datafiles available on zenodo at the same time. 

Additional, two other changes need to be made at the same time:
- change machine strategy such that we have a global_cache (e.g., for datasets) and a local_cache (for the output for a given run). 
- allow users to input use a local dataset (via a user specified yaml file). I think this will be important for testing new datasets and give the option to use something that is not available publicly.

**Comment by chrisiacovella** [comment]
Regarding revising the .yaml files... 

To allow us to have a single hdf5 data loader, rather than individual python classes that inherit from the HDF5Dataset, we need to put more information in the .yaml files. 

Since we now must define the `properties_of_interest` and their association with internal variables in the input file, I think we only need to define `available_properties` in the  dataset specific .yaml file. This works with our philosophy of no default parameters; currently the classes do have a set of default properties of interest and their association.   The `available_properties` should be associated with each version (as opposed to global), since the properties in a datafile could change in a new version (that might in fact be the reason for the new version). 

We also need to define the `atomic_self_energies` in the .yaml file, as this is something else defined in each class. 
Unlike `available_properties`,  I think `atomic_self_energies` should be a global property that applies to all versions, as this should be primarily a consequence of the level of theory used to compute the energy.  Note, these can be recomputed at run time for any individual version. 

We do not need to define the property/unit type association anymore.  All the HDF5 files now generated with modelforge.curate class provide the property_type, which, when combined with the global units class, will allow us to check and convert units (as noted above this will require changing the dataset loader function to use the global units, which I think is a good idea).  

Note the new .yaml files will also have an hdf5_schema tag which we can use to check for compatibility with the code (note this is not read from the hdf5 file itself...I feel this could be useful if we change how things are encoded, we can have version specific functions to avoid having to go back and regenerated curated datasets). 

To make things more transparent, I've added to the .yaml files a global description about the dataset (essentially what is in the header of the python file for each class currently).  Furthermore, each version will get an "about" bit of text, which mostly copies what is in the zenodo record description.  It should then be very easy to write a few scripts to automatically generate documentation pages about each dataset and the versions available. 

From the .yaml file,  I have removed the field that lists the name of processed data file (i.e., the .npz file); this can just be determined dynamically.  I think actually we want to remove checking for the .npz files altogether.  As noted the .hdf5 files will be part of the "global" cache, and each run will go into a local_cache; the .npz file should be part of the "local" cache, as it depends on the properties of interest chosen and other filtering options.  Generating this is not expensive so we can just generate each time. 

And example of a snippet of what a new .yaml file will look like is below. 

I've also grouped all the things that apply to zenodo (or presumably could apply to figshare or any other service) under "remote_record".  To allow for local datasets (very useful for testing or datasets you don't want available to the public), we can just have a tag that is "local_record" that just provides the file path to the local hdf5 file.  When defining the input .toml files, we should be able to specify the path to a local .yaml file, which would have a "local_record" defined.  
```
dataset: tmqm_xtb
latest: PdZnFeCuNiPtIrRhCrAg_T100K_v1.1
latest_test: nc_1000_v1.1

atomic_self_energies:
  H: -1346.9991827591664 * kilojoule_per_mole
  C: -5617.968751828634 * kilojoule_per_mole
  N: -7672.109298341974 * kilojoule_per_mole
  O: -10704.649544039614 * kilojoule_per_mole
  F: -12450.413867238472 * kilojoule_per_mole
  Ir: -6598.040049917221 * kilojoule_per_mole
  Pt: -8576.086025878865 * kilojoule_per_mole
  P: -12100.053458428218 * kilojoule_per_mole
  S: -4944.219007863149 * kilojoule_per_mole
  Cl: -7938.35372876674 * kilojoule_per_mole
  Cr: -12369.173271985948 * kilojoule_per_mole
  Fe: -9663.693466916478 * kilojoule_per_mole
  Ni: -1252.3530347274261 * kilojoule_per_mole
  Cu: -10894.410447334463 * kilojoule_per_mole
  Zn: -10182.310751929233 * kilojoule_per_mole
  Br: -11739.997032286365 * kilojoule_per_mole
  Rh: -9590.608153082434 * kilojoule_per_mole
  Pd: -9713.417530536652 * kilojoule_per_mole
  Ag: -11641.150291664564 * kilojoule_per_mole

PdZnFeCu_T100K_single_config_v1.0:
  hdf5_schema: 2
  doi: 10.5281/zenodo.15021819
  available_properties:
    - positions
    - atomic_numbers
    - total_charge
    - forces
    - dipole_moment_per_system
    - energies
    - partial_charges
  about:  "This dataset contains 23134 unique systems with 23134 total configurations (1 configuration per system)  
           Each configuration corresponds to the geometry distributed as part of the original tmQM dataset. with
           no MD sampling applied.
             
           This dataset is limited to systems that contain transition metals Pd, Zn, Fe,  or Cu, 
           and also only contain elements C, H, P, S, O, N, F, Cl, or Br. 
          
          This dataset was generated starting from the tmQM dataset; the original tmQM repository 
          (https://github.com/uiocompcat/tmQM) was forked and a release made that corresponds to the data committed
          on 13 August 2024 (https://github.com/chrisiacovella/tmQM/releases/tag/2024Aug13).
          
          The tblite package was used to evaluate the energetic of the system using the gfn2-xtb formalism, 
          using the calculator as part of the Atomic Simulation Environment (ASE), calculated at accuracy level 1. 

          Scripts used to perform the sampling can be found at  https://github.com/chrisiacovella/xtb_config_gen"
  remote_record:
    doi: 10.5281/zenodo.15021819
    url: https://zenodo.org/records/15021819/files/tmqm_xtb_dataset_PdZnFeCu_T100_first_v1.0.hdf5.gz
    gz_data_file:
      length: 96544047
      md5: cb86823c62d2127c209cded323c03eef
      name: tmqm_xtb_dataset_PdZnFeCu_T100K_single_config_v1.hdf5.gz
    hdf5_data_file:
      md5: 96811817c3d65fdbe1c3691125ff0664
      name: tmqm_xtb_dataset_PdZnFeCu_T100K_single_config_v1.hdf5

description: "The tmQM-xtb dataset performs GFN2-xTB-based MD simulations starting from the energy-minimized geometries 
    in the tmQM dataset.  

    The original tmQM dataset contains the geometries and properties of mononuclear complexes extracted from the
    Cambridge Structural Database, including Werner, bioinorganic, and organometallic complexes based on a large
    variety of organic ligands and 30 transition metals (the 3d, 4d, and 5d from groups 3 to 12).
    All complexes are closed-shell, with a formal charge in the range {+1, 0, −1}e .

    Original Citation:

    David Balcells and Bastian Bjerkem Skjelstad,
    tmQM Dataset—Quantum Geometries and Properties of 86k Transition Metal Complexes
    Journal of Chemical Information and Modeling 2020 60 (12), 6135-6146
    DOI: 10.1021/acs.jcim.0c01041 "
```
